name: Deploy frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout
          uses: actions/checkout@v2

        - name: Add remote origin
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_ZELLNER_API_KEY }}@git.heroku.com/aume-frontend.git

        - name: Deploy frontend to heroku
          run: git push --force heroku `git subtree split --prefix server HEAD`:master
