name: Build and validate frontend

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint
  
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
    
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend && npm install
      - run: cd frontend && npm run build --release