name: Build and validate frontend

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Installing project dependencies
    - run: npm install
    - name: Linting the project
    - run: cd frontend && npm run lint
      
  # build-dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #   - name: Installing project dependencies
  #   - run: npm install
  #   - name: Building the project for development
  #   - run: cd frontend && npm run build

  # build-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #   - name: Installing project dependencies
  #   - run: npm install
  #   - name: Building the project for production
  #   - run: cd frontend && npm run build --release